namespace Unscrambler;

public static class Stations
{
    // Official NS station names (Nederlandse Spoorwegen)
    // Non-letter characters (spaces, dashes, apostrophes) are kept here for display,
    // but are ignored during anagram matching.
    public static readonly string[] All =
    [
        // A
        "Almelo",
        "Almelo de Riet",
        "Almere Buiten",
        "Almere Centrum",
        "Almere Muziekwijk",
        "Almere Oostvaarders",
        "Almere Poort",
        "Alphen aan den Rijn",
        "Amersfoort",
        "Amersfoort Schothorst",
        "Amersfoort Vathorst",
        "Amsterdam Amstel",
        "Amsterdam Bijlmer ArenA",
        "Amsterdam Centraal",
        "Amsterdam Holendrecht",
        "Amsterdam Lelylaan",
        "Amsterdam Muiderpoort",
        "Amsterdam RAI",
        "Amsterdam Science Park",
        "Amsterdam Sloterdijk",
        "Amsterdam Watergraafsmeer",
        "Amsterdam Zuid",
        "Apeldoorn",
        "Apeldoorn de Maten",
        "Apeldoorn Osseveld",
        "Arkel",
        "Arnhem",
        "Arnhem Centraal",
        "Arnhem Presikhaaf",
        "Arnhem Velperpoort",
        "Assen",

        // B
        "Baarn",
        "Barendrecht",
        "Barneveld Noord",
        "Barneveld Zuid",
        "Bathmen",
        "Bergen op Zoom",
        "Best",
        "Beverwijk",
        "Bilthoven",
        "Blerick",
        "Bloemendaal",
        "Bodegraven",
        "Boxmeer",
        "Boxtel",
        "Breda",
        "Breukelen",
        "Brummen",
        "Bunnik",
        "Bussum Zuid",

        // C
        "Castricum",
        "Capelle Schollevaar",
        "Cuijk",

        // D
        "Delfgauw",
        "Delft",
        "Delft Zuid",
        "Den Haag Centraal",
        "Den Haag HS",
        "Den Haag Laan v NOI",
        "Den Haag Moerwijk",
        "Den Haag Ypenburg",
        "Den Haag Mariahoeve",
        "Deurne",
        "Deventer",
        "Diemen",
        "Diemen Zuid",
        "Dieren",
        "Doetinchem",
        "Doetinchem De Huet",
        "Dordrecht",
        "Dordrecht Zuid",
        "Dronten",
        "Drunen",
        "Duivendrecht",

        // E
        "Ede-Wageningen",
        "Eindhoven",
        "Eindhoven Centraal",
        "Eindhoven Beukenlaan",
        "Eindhoven Strijp-S",
        "Elst",
        "Emmen",
        "Emmen Zuid",
        "Enkhuizen",
        "Enschede",
        "Enschede De Eschmarke",
        "Etten-Leur",

        // F
        "Franeker",

        // G
        "Geldermalsen",
        "Gilze-Rijen",
        "Gouda",
        "Gouda Goverwelle",
        "Groningen",
        "Grou-Jirnsum",

        // H
        "Haarlem",
        "Haarlem Spaarnwoude",
        "Hardenberg",
        "Harderwijk",
        "Harlingen",
        "Harlingen Haven",
        "Heemskerk",
        "Heemstede-Aerdenhout",
        "Heerenveen",
        "Heerlen",
        "Heeze",
        "Heiloo",
        "Helmond",
        "Helmond Brandevoort",
        "Helmond Brouwhuis",
        "Helpman",
        "Hengelo",
        "Hertogenbosch",
        "Hillegom",
        "Hilversum",
        "Hilversum Media Park",
        "Hilversum Sportpark",
        "Hoevelaken",
        "Holten",
        "Hoofddorp",
        "Hoogeveen",
        "Hoorn",
        "Hoorn Kersenboogerd",
        "Horst-Sevenum",
        "Houten",
        "Houten Castellum",

        // I
        "IJlst",

        // K
        "Kampen",
        "Kampen Zuid",
        "Kapelle-Biezelinge",
        "Kesteren",
        "Klazienaveen",
        "Kronenberg",

        // L
        "Lage Zwaluwe",
        "Leeuwarden",
        "Leiden",
        "Leiden Centraal",
        "Leiden Lammenschans",
        "Leiderdorp",
        "Leidschendam-Voorburg",
        "Lelystad Centrum",
        "Lelystad",
        "Lichtenvoorde-Groenlo",
        "Lisse",
        "Loon op Zand",

        // M
        "Maarn",
        "Maarssen",
        "Maastricht",
        "Maastricht Randwyck",
        "Marienberg",
        "Meppel",
        "Middelburg",
        "Middelharnis",
        "Mijdrecht",

        // N
        "Naarden-Bussum",
        "Nijkerk",
        "Nijmegen",
        "Nijmegen Dukenburg",
        "Nijmegen Goffert",
        "Nijmegen Heyendaal",
        "Nijmegen Lent",
        "Noord",
        "Nunspeet",

        // O
        "Oldenzaal",
        "Ommen",
        "Oosterhout",
        "Oss",
        "Oss West",
        "Oudenbosch",

        // P
        "Papendrecht",
        "Purmerend",
        "Purmerend Weidevenne",

        // R
        "Rhenen",
        "Ridderkerk De Ridderhof",
        "Ridderkerk Noord",
        "Rijen",
        "Roermond",
        "Roosendaal",
        "Rotterdam Alexander",
        "Rotterdam Blaak",
        "Rotterdam Centraal",
        "Rotterdam Lombardijen",
        "Rotterdam Noord",
        "Rotterdam Stadion",
        "Rotterdam Zuid",
        "Ruurlo",

        // S
        "Schagen",
        "Schiedam Centrum",
        "Sittard",
        "Sliedrecht",
        "Sneek",
        "Sneek Noord",
        "Soest",
        "Soest Zuid",
        "Spaubeek",
        "Sprundel",
        "Steenwijk",
        "Susteren",

        // T
        "Tegelen",
        "Tilburg",
        "Tilburg Universiteit",
        "Tilburg Reeshof",

        // U
        "Utrecht Centraal",
        "Utrecht Lunetten",
        "Utrecht Maliebaan",
        "Utrecht Overvecht",
        "Utrecht Vaartsche Rijn",
        "Utrecht Zuilen",

        // V
        "Veendam",
        "Veenendaal Centrum",
        "Veenendaal De Klomp",
        "Venlo",
        "Venray",
        "Vlissingen",
        "Voorhout",
        "Voorschoten",
        "Vught",

        // W
        "Wageningen",
        "Weert",
        "Weesp",
        "Winterswijk",
        "Woerden",
        "Wormerveer",

        // Z
        "Zaandam",
        "Zeist",
        "Zevenbergen",
        "Zoetermeer",
        "Zutphen",
        "Zwolle",

        // Additional stations
        "Abcoude",
        "Akkrum",
        "Alkmaar",
        "Alkmaar Noord",
        "Amstelveen Westwijk",
        "Amstel",
        "Arcen",
        "Avenhorn",
        "Balk",
        "Baflo",
        "Bentheim",
        "Berkel en Rodenrijs",
        "Bladel",
        "Blaricum",
        "Boskoop",
        "Brouwershaven",
        "Brunssum",
        "Coevorden",
        "De Klomp",
        "De Vink",
        "Dedemsvaart",
        "Den Helder",
        "Den Helder Zuid",
        "Denekamp",
        "Dokkum",
        "Doldersum",
        "Driebergen-Zeist",
        "Dronten",
        "Duiven",
        "Dwingelo",
        "Echteld",
        "Eersel",
        "Elburg",
        "Emmeloord",
        "Ermelo",
        "Franeker",
        "Geldrop",
        "Gemert",
        "Goes",
        "Gorinchem",
        "Gorssel",
        "Goudriaan-Ottoland",
        "Groenlo",
        "Grou",
        "Haps",
        "Haren",
        "Harenkarspel",
        "Hedel",
        "Heerenveen",
        "Heerhugowaard",
        "Helmond",
        "Hengelo",
        "Herbayum",
        "Herten",
        "Hindeloopen",
        "Hoensbroek",
        "Hoevelaken",
        "Hoorn",
        "Hoogezand-Sappemeer",
        "Huizen",
        "IJmuiden",
        "Joure",
        "Julianadorp",
        "Kaatsheuvel",
        "Kerkrade Centrum",
        "Kerkrade West",
        "Kinderdijk",
        "Klundert",
        "Kollum",
        "Lage Zwaluwe",
        "Landgraaf",
        "Langenboom",
        "Leerdam",
        "Lemmer",
        "Lichtenvoorde",
        "Lisse",
        "Lochem",
        "Made",
        "Medemblik",
        "Meppel",
        "Middelburg",
        "Mill",
        "Moordrecht",
        "Naaldwijk",
        "Naarden",
        "Nieuw-Amsterdam",
        "Nieuwegein Noord",
        "Nieuwegein Zuid",
        "Nieuwerkerk aan den IJssel",
        "Nijkerk",
        "Obdam",
        "Oisterwijk",
        "Oldebroek",
        "Oldenzaal",
        "Oost",
        "Oosterhout",
        "Opsterland",
        "Oudewater",
        "Pannerden",
        "Papendrecht",
        "Pijnacker",
        "Pijnacker Noord",
        "Puttershoek",
        "Raamsdonksveer",
        "Raalte",
        "Rheden",
        "Ridderkerk",
        "Rockanje",
        "Rossum",
        "Rozendaal",
        "Schagen",
        "Schiedam Nieuwland",
        "Schipluiden",
        "Sloehaven",
        "Sloten",
        "Smilde",
        "Spijkenisse",
        "Spijkenisse Centrum",
        "Stadskanaal",
        "Staphorst",
        "Stein",
        "Strijen",
        "Swifterbant",
        "Tiel",
        "Tolkamer",
        "Tuitjenhorn",
        "Twee Steden",
        "Ubbergen",
        "Uitgeest",
        "Uithoorn",
        "Urk",
        "Valkenburg",
        "Valkenswaard",
        "Veen",
        "Veghel",
        "Veldhoven",
        "Velp",
        "Venhuizen",
        "Vianen",
        "Vlaardingen",
        "Vlaardingen Centrum",
        "Vlaardingen Oost",
        "Vlissingen Souburg",
        "Volendam",
        "Voorburg",
        "Voorst-Empe",
        "Vriezenveen",
        "Waalwijk",
        "Waddinxveen",
        "Waddinxveen Noord",
        "Wanssum",
        "Warmond",
        "Wassenaar",
        "Wervershoof",
        "Wezel",
        "Wierden",
        "Wijchen",
        "Wijk bij Duurstede",
        "Willemstad",
        "Winschoten",
        "Winterswijk West",
        "Wisch",
        "Wittem",
        "Wolvega",
        "Workum",
        "Wormer",
        "Wouw",
        "Woudenberg",
        "Woudrichem",
        "Zaandijk Zaanse Schans",
        "Zaltbommel",
        "Zevenaar",
        "Zierikzee",
        "Zierikzee Haven",
        "Zoetermeer Oost",
        "Zuidbroek",
    ];
}
