namespace Unscrambler;

public static class Stations
{
    // Official NS station names (Nederlandse Spoorwegen)
    // Non-letter characters (spaces, dashes, apostrophes) are kept here for display,
    // but are ignored during anagram matching.
    public static readonly string[] All =
    [
        // A
        "Aalten",
        "Abcoude",
        "Akkrum",
        "Alkmaar",
        "Alkmaar Noord",
        "Almelo",
        "Almelo de Riet",
        "Almere Buiten",
        "Almere Centrum",
        "Almere Muziekwijk",
        "Almere Oostvaarders",
        "Almere Parkwijk",
        "Almere Poort",
        "Alphen aan den Rijn",
        "Amersfoort",
        "Amersfoort Schothorst",
        "Amersfoort Vathorst",
        "Amstel",
        "Amstelveen Westwijk",
        "Amsterdam Amstel",
        "Amsterdam Bijlmer ArenA",
        "Amsterdam Centraal",
        "Amsterdam Holendrecht",
        "Amsterdam Lelylaan",
        "Amsterdam Muiderpoort",
        "Amsterdam RAI",
        "Amsterdam Science Park",
        "Amsterdam Sloterdijk",
        "Amsterdam Watergraafsmeer",
        "Amsterdam Zuid",
        "Anna Paulowna",
        "Apeldoorn",
        "Apeldoorn de Maten",
        "Apeldoorn Osseveld",
        "Appingedam",
        "Arcen",
        "Arkel",
        "Arnemuiden",
        "Arnhem",
        "Arnhem Centraal",
        "Arnhem Presikhaaf",
        "Arnhem Velperpoort",
        "Arnhem Zuid",
        "Assen",
        "Avenhorn",

        // B
        "Baarn",
        "Baflo",
        "Balk",
        "Barendrecht",
        "Barneveld Centrum",
        "Barneveld Noord",
        "Barneveld Zuid",
        "Bathmen",
        "Bedum",
        "Beek-Elsloo",
        "Beesd",
        "Beilen",
        "Bentheim",
        "Bergen op Zoom",
        "Berkel en Rodenrijs",
        "Best",
        "Beverwijk",
        "Bilthoven",
        "Bladel",
        "Blaricum",
        "Blerick",
        "Bloemendaal",
        "Bodegraven",
        "Borne",
        "Boskoop",
        "Boskoop Snijdelwijk",
        "Boven Hardinxveld",
        "Bovenkarspel Flora",
        "Bovenkarspel-Grootebroek",
        "Boxmeer",
        "Boxtel",
        "Breda",
        "Breda Prinsenbeek",
        "Breukelen",
        "Brouwershaven",
        "Brummen",
        "Brunssum",
        "Buitenpost",
        "Bunde",
        "Bunnik",
        "Bussum Zuid",

        // C
        "Capelle Schollevaar",
        "Castricum",
        "Chevremont",
        "Coevorden",
        "Cuijk",
        "Culemborg",

        // D
        "Daarlerveen",
        "Dalen",
        "Dalfsen",
        "De Klomp",
        "De Vink",
        "De Westereen",
        "Dedemsvaart",
        "Deinum",
        "Delden",
        "Delfgauw",
        "Delft",
        "Delft Zuid",
        "Delfzijl",
        "Delfzijl West",
        "Den Dolder",
        "Den Haag Centraal",
        "Den Haag HS",
        "Den Haag Laan v NOI",
        "Den Haag Mariahoeve",
        "Den Haag Moerwijk",
        "Den Haag Ypenburg",
        "Den Helder",
        "Den Helder Zuid",
        "Denekamp",
        "Deurne",
        "Deventer",
        "Deventer Colmschate",
        "Didam",
        "Diemen",
        "Diemen Zuid",
        "Dieren",
        "Doetinchem",
        "Doetinchem De Huet",
        "Dokkum",
        "Doldersum",
        "Dordrecht",
        "Dordrecht Stadspolders",
        "Dordrecht Zuid",
        "Driebergen-Zeist",
        "Driehuis",
        "Dronryp",
        "Dronten",
        "Drunen",
        "Duiven",
        "Duivendrecht",
        "Dwingelo",

        // E
        "Echt",
        "Echteld",
        "Ede Centrum",
        "Ede-Wageningen",
        "Eemshaven",
        "Eersel",
        "Eijsden",
        "Eindhoven",
        "Eindhoven Beukenlaan",
        "Eindhoven Centraal",
        "Eindhoven Stadion",
        "Eindhoven Strijp-S",
        "Elburg",
        "Elst",
        "Emmeloord",
        "Emmen",
        "Emmen Zuid",
        "Enkhuizen",
        "Enschede",
        "Enschede De Eschmarke",
        "Enschede Kennispark",
        "Ermelo",
        "Etten-Leur",
        "Eygelshoven",
        "Eygelshoven Markt",

        // F
        "Feanwâlden",
        "Franeker",

        // G
        "Gaanderen",
        "Geldermalsen",
        "Geldrop",
        "Geleen Oost",
        "Geleen-Lutterade",
        "Gemert",
        "Gilze-Rijen",
        "Glanerbrug",
        "Goes",
        "Goor",
        "Gorinchem",
        "Gorssel",
        "Gouda",
        "Gouda Goverwelle",
        "Goudriaan-Ottoland",
        "Gramsbergen",
        "Grijpskerk",
        "Groenlo",
        "Groningen",
        "Groningen Europapark",
        "Groningen Noord",
        "Grou",
        "Grou-Jirnsum",

        // H
        "Haarlem",
        "Haarlem Spaarnwoude",
        "Halfweg-Zwanenburg",
        "Haps",
        "Hardenberg",
        "Harderwijk",
        "Hardinxveld Blauwe Zoom",
        "Hardinxveld-Giessendam",
        "Haren",
        "Harenkarspel",
        "Harlingen",
        "Harlingen Haven",
        "Hedel",
        "Heemskerk",
        "Heemstede-Aerdenhout",
        "Heerenveen",
        "Heerhugowaard",
        "Heerlen",
        "Heerlen Woonboulevard",
        "Heeze",
        "Heiloo",
        "Heino",
        "Helmond",
        "Helmond 't Hout",
        "Helmond Brandevoort",
        "Helmond Brouwhuis",
        "Helpman",
        "Hemmen-Dodewaard",
        "Hengelo",
        "Hengelo Gezondheidspark",
        "Hengelo Oost",
        "Herbayum",
        "Herten",
        "Hertogenbosch",
        "Hillegom",
        "Hilversum",
        "Hilversum Media Park",
        "Hilversum Sportpark",
        "Hindeloopen",
        "Hoensbroek",
        "Hoevelaken",
        "Hollandsche Rading",
        "Holten",
        "Hoofddorp",
        "Hoogeveen",
        "Hoogezand-Sappemeer",
        "Hoogkarspel",
        "Hoorn",
        "Hoorn Kersenboogerd",
        "Horst-Sevenum",
        "Houten",
        "Houten Castellum",
        "Houthem-Sint Gerlach",
        "Huizen",
        "Hurdegaryp",

        // I
        "IJlst",
        "IJmuiden",

        // J
        "Joure",
        "Julianadorp",

        // K
        "Kaatsheuvel",
        "Kampen",
        "Kampen Zuid",
        "Kapelle-Biezelinge",
        "Kerkrade Centrum",
        "Kerkrade West",
        "Kesteren",
        "Kinderdijk",
        "Klarenbeek",
        "Klazienaveen",
        "Klimmen-Ransdaal",
        "Klundert",
        "Kollum",
        "Koog aan de Zaan",
        "Koudum-Molkwerum",
        "Krabbendijke",
        "Krommenie-Assendelft",
        "Kronenberg",
        "Kropswolde",
        "Kruiningen-Yerseke",

        // L
        "Lage Zwaluwe",
        "Landgraaf",
        "Langenboom",
        "Lansingerland-Zoetermeer",
        "Leerdam",
        "Leeuwarden",
        "Leeuwarden Camminghaburen",
        "Leiden",
        "Leiden Centraal",
        "Leiden Lammenschans",
        "Leiderdorp",
        "Leidschendam-Voorburg",
        "Lelystad",
        "Lelystad Centrum",
        "Lemmer",
        "Lichtenvoorde",
        "Lichtenvoorde-Groenlo",
        "Lisse",
        "Lochem",
        "Loon op Zand",
        "Loppersum",
        "Lunteren",

        // M
        "Maarheeze",
        "Maarn",
        "Maarssen",
        "Maastricht",
        "Maastricht Noord",
        "Maastricht Randwyck",
        "Made",
        "Mantgum",
        "Marienberg",
        "Martenshoek",
        "Medemblik",
        "Meerssen",
        "Meppel",
        "Middelburg",
        "Middelharnis",
        "Mijdrecht",
        "Mill",
        "Mook-Molenhoek",
        "Moordrecht",

        // N
        "Naaldwijk",
        "Naarden",
        "Naarden-Bussum",
        "Nieuw-Amsterdam",
        "Nieuw-Vennep",
        "Nieuwegein Noord",
        "Nieuwegein Zuid",
        "Nieuwerkerk aan den IJssel",
        "Nijkerk",
        "Nijmegen",
        "Nijmegen Dukenburg",
        "Nijmegen Goffert",
        "Nijmegen Heyendaal",
        "Nijmegen Lent",
        "Nijverdal",
        "Noord",
        "Nunspeet",
        "Nuth",

        // O
        "Obdam",
        "Oisterwijk",
        "Oldebroek",
        "Oldenzaal",
        "Olst",
        "Ommen",
        "Oost",
        "Oosterbeek",
        "Oosterhout",
        "Opheusden",
        "Opsterland",
        "Oss",
        "Oss West",
        "Oudenbosch",
        "Oudewater",
        "Overveen",

        // P
        "Pannerden",
        "Papendrecht",
        "Pijnacker",
        "Pijnacker Noord",
        "Purmerend",
        "Purmerend Overwhere",
        "Purmerend Weidevenne",
        "Putten",
        "Puttershoek",

        // R
        "Raalte",
        "Raamsdonksveer",
        "Ravenstein",
        "Reuver",
        "Rheden",
        "Rhenen",
        "Ridderkerk",
        "Ridderkerk De Ridderhof",
        "Ridderkerk Noord",
        "Rijen",
        "Rijssen",
        "Rijswijk",
        "Rilland-Bath",
        "Rockanje",
        "Roermond",
        "Roodeschool",
        "Roosendaal",
        "Rosmalen",
        "Rossum",
        "Rotterdam Alexander",
        "Rotterdam Blaak",
        "Rotterdam Centraal",
        "Rotterdam Lombardijen",
        "Rotterdam Noord",
        "Rotterdam Stadion",
        "Rotterdam Zuid",
        "Rozendaal",
        "Ruurlo",

        // S
        "'s-Hertogenbosch Oost",
        "Santpoort Noord",
        "Santpoort Zuid",
        "Sassenheim",
        "Sauwerd",
        "Schagen",
        "Scheemda",
        "Schiedam Centrum",
        "Schiedam Nieuwland",
        "Schin op Geul",
        "Schinnen",
        "Schiphol",
        "Schipluiden",
        "Sittard",
        "Sliedrecht",
        "Sliedrecht Baanhoek",
        "Sloehaven",
        "Sloten",
        "Smilde",
        "Sneek",
        "Sneek Noord",
        "Soest",
        "Soest Zuid",
        "Soestdijk",
        "Spaubeek",
        "Spijkenisse",
        "Spijkenisse Centrum",
        "Sprundel",
        "Stadskanaal",
        "Staphorst",
        "Stavoren",
        "Stedum",
        "Steenwijk",
        "Stein",
        "Strijen",
        "Susteren",
        "Swalmen",
        "Swifterbant",

        // T
        "'t Harde",
        "Tegelen",
        "Terborg",
        "Tiel",
        "Tiel Passewaaij",
        "Tilburg",
        "Tilburg Reeshof",
        "Tilburg Universiteit",
        "Tolkamer",
        "Tuitjenhorn",
        "Twee Steden",
        "Twello",

        // U
        "Ubbergen",
        "Uitgeest",
        "Uithoorn",
        "Uithuizen",
        "Uithuizermeeden",
        "Urk",
        "Usquert",
        "Utrecht Centraal",
        "Utrecht Leidsche Rijn",
        "Utrecht Lunetten",
        "Utrecht Maliebaan",
        "Utrecht Overvecht",
        "Utrecht Terwijde",
        "Utrecht Vaartsche Rijn",
        "Utrecht Zuilen",

        // V
        "Valkenburg",
        "Valkenswaard",
        "Varsseveld",
        "Veen",
        "Veendam",
        "Veenendaal Centrum",
        "Veenendaal De Klomp",
        "Veenendaal West",
        "Veghel",
        "Veldhoven",
        "Velp",
        "Venhuizen",
        "Venlo",
        "Venray",
        "Vianen",
        "Vierlingsbeek",
        "Vlaardingen",
        "Vlaardingen Centrum",
        "Vlaardingen Oost",
        "Vleuten",
        "Vlissingen",
        "Vlissingen Souburg",
        "Voerendaal",
        "Volendam",
        "Voorburg",
        "Voorhout",
        "Voorschoten",
        "Voorst-Empe",
        "Vorden",
        "Vriezenveen",
        "Vroomshoop",
        "Vught",

        // W
        "Waalwijk",
        "Waddinxveen",
        "Waddinxveen Noord",
        "Waddinxveen Triangel",
        "Wageningen",
        "Wanssum",
        "Warffum",
        "Warmond",
        "Wassenaar",
        "Weert",
        "Weesp",
        "Wehl",
        "Wervershoof",
        "Westervoort",
        "Wezel",
        "Wezep",
        "Wierden",
        "Wijchen",
        "Wijhe",
        "Wijk bij Duurstede",
        "Willemstad",
        "Winschoten",
        "Winsum",
        "Winterswijk",
        "Winterswijk West",
        "Wisch",
        "Wittem",
        "Woerden",
        "Wolfheze",
        "Wolvega",
        "Workum",
        "Wormer",
        "Wormerveer",
        "Woudenberg",
        "Woudrichem",
        "Wouw",

        // Z
        "Zaandam",
        "Zaandam Kogerveld",
        "Zaandijk Zaanse Schans",
        "Zaltbommel",
        "Zandvoort aan Zee",
        "Zeist",
        "Zetten-Andelst",
        "Zevenaar",
        "Zevenbergen",
        "Zierikzee",
        "Zierikzee Haven",
        "Zoetermeer",
        "Zoetermeer Oost",
        "Zuidbroek",
        "Zuidhorn",
        "Zutphen",
        "Zwijndrecht",
        "Zwolle",
        "Zwolle Stadshagen",
    ];
}